id: amd-soc15
language: cpp
context_vars: [adev, adapt]
symbol_prefixes: [reg, mm, smn]
wrappers:
  SOC15_REG_OFFSET:
    symbol_arg: 2
    access: address
  SOC15_REG_ENTRY:
    symbol_arg: 2
    access: address
  WREG32_SOC15:
    symbol_arg: 2
    access: write
  RREG32_SOC15:
    symbol_arg: 2
    access: read
  WREG32_SOC15_IP:
    symbol_arg: 2
    access: write
  RREG32_SOC15_IP:
    symbol_arg: 2
    access: read
  WREG32_SOC15_OFFSET:
    symbol_arg: 2
    access: write
  RREG32_SOC15_OFFSET:
    symbol_arg: 2
    access: read
  WREG32_SOC15_NO_KIQ:
    symbol_arg: 2
    access: write
  RREG32_SOC15_NO_KIQ:
    symbol_arg: 2
    access: read
  WREG32_SOC15_RLC:
    symbol_arg: 2
    access: write
  RREG32_SOC15_RLC:
    symbol_arg: 2
    access: read
  WREG32_SOC15_RLC_SHADOW:
    symbol_arg: 2
    access: write
